### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by iProgYou** [frmendez21/MyTube#6]
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
- I can't think of any scenarios where you would need `GET /api/comments/:id` or `GET /api/comments`. The later could just be fetched when you do `GET /api/videos/:id` and the former is unnecessary.

**Comment by frmendez21** [comment]
Updated GET routes for comments, remove both GET routes
