### ISSUE TITLE
Videos MVP

### ISSUE THREAD

**Issue by frmendez21** [frmendez21/MyTube#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by iProgYou** [comment]
- I think you may need some more seeds. Right now the splash page looks too sparse
- make sure you have some sort of visible border between the navbar and the main page
- Dropdown behavior is a bit erratic
- Try to make the page look exactly like youtube does

**Comment by iProgYou** [comment]
- Videos need description, author etc
- top right icons need to be spaced more 
- I think youtube doesn't use plain white. It is somewhat jarring on the video show page
-  the icon letters are oval in some cases
- the video show needs a navbar border
- navbar needs to be fixed
- video index needs to be centered
- For the video form, make sure to line up the upload video and photo boxes are lined up with the title and description

**Comment by iProgYou** [comment]
- Description text looks a bit large and bolded
- Video title needs a bit of top margin to move it away from the video itself
- I think it would look better if you could turn the background of the video black as opposed to white. Though I am not if the background is part of the video or the video player
- Round the edges for the upload forms. It will make it look less 90's
- It  looks like the borders on the description is 1px and on the upload forms is 2px
- Fix oval icon on upload page
